#!/bin/sh

# doas not required for some system commands
for command in mount umount loginctl reboot poweroff shutdown pacman sv; do
	alias $command="doas $command"
done; unset command

# Utilities configuration
# Colored output, verbosity and protection
# against overwriting.
alias \
	ls="ls --color=auto --group-directories-first" \
	grep="grep -i --color=auto" \
	diff="diff --color=auto" \
	rm="rm -Iv" \
	cp="cp -riv" \
	mv="mv -iv" \
	vidir="vidir -v" \
	mkdir="mkdir -p"

# pacman, yay
alias \
	p="doas pacman" \
	y="yay" \
	pyu="doas pacman -Syu"

# Use neovim for vim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Other abbreviations
alias \
	v="$EDITOR" \
	vi="$EDITOR" \
	l="ls" \
	ll="ls -A" \
	lll=" ls -lAcht" \
	lr="ls -R" \
	lh="ls -lAcht | head -n 30" \
	lhr="ls -lArcht | head -n 30" \
	g="grep" \
	lg="l | g" \
	gi="git" \
	gst="git status" \
	gcl="git clone" \
	gdi="git diff" \
	gad="git add" \
	glo="git log" \
	gre="git restore" \
	gcm="git commit -m" \
	gca="git commit -a" \
	t="tmux" \
	ta="tmux attach-session" \
	tl="tmux ls" \
	qtb="~/.local/bin/qtb" \
	z="zathura" \
	ppv="pipe-viewer" \
	pph="pipe-viewer -wv" \
	pps="pipe-viewer -S" \
	hstr="hh" \
	qbt="qbittorrent-nox --daemon" \
	mm="mpc" \
	ma="mpc add" \
	mc="mpc clear" \
	mp="mpc playlist" \
	mu="mpc up" \
	mt="mpc toggle" \
	b="beet" \
	bi="beet import" \
	br="beet remove" \
	be="beet edit" \
	ytdl="yt-dlp" \
	iv="nsxiv -a" \
	ivu="nsxiv-url" \
	yt="ytfzf" \
	ncdu="ncdu --color off" \
	zzz="loginctl suspend" \
	rs="rsync -rvP" \
	c="calcurse" \
	t="toot" \
	tt="toot tui" \
	tp="toot post -v unlisted -e" \
	tn="toot notifications"

# External storage
alias \
	m3m="pmount -e /dev/sdb1 m3" \
	m3u="pumount /media/m3" \
	mtpm="simple-mtpfs --device 1 /media/android" \
	mtpu="fusermount -u /media/android"

# Managing wi-fi and bluetooth
alias \
	wscan="iwctl station wlan0 scan" \
	wgn="iwctl station wlan0 get-networks" \
	bhp="bluetoothctl connect 4C:65:A8:97:2F:9E" \
	wup="doas sv up iwd && doas ip link set dev wlan0 up" \
	wdown="doas ip link set dev wlan0 down && doas sv down iwd" \
	bup="doas sv up bluetoothd && bluetoothctl power on && bluetoothctl connect 4C:65:A8:97:2F:9E" \
	bdown="bluetoothctl disconnect 4C:65:A8:97:2F:9E && bluetoothctl power off && doas sv down bluetoothd"

# Other aliases
alias \
	abook="abook -C ~/.config/abook/abookrc --datafile ~/.local/share/abook/addressbook" \
	wi="vim -c VimwikiIndex" \
	di="vim -c VimwikiDiaryIndex" \
	www="w3m -B" \
	mdcat="mdcat -p" \
	ccat="highlight -O ansi" \
	bat="bat --theme gruvbox-dark" \
	sca="scrcpy" \
	vsv="doas rsm" \
	ph="cat /var/log/pacman.log" \
	mpd="mpd && mpc up && mpdscribble --conf ~/.config/mpd/mpdscribble.conf"
