#!/bin/sh

# Root commands
for command in mount umount loginctl reboot poweroff shutdown pacman; do
    alias "$command"="sudo $command"
done
unset command

# Neovim
alias dv="sudo nvim"

# Utilities
alias \
    grep="grep -i --color=auto" \
    diff="diff --color=auto" \
    rm="rm -Iv" \
    cp="cp -riv" \
    mv="mv -iv" \
    vidir="vidir -v" \
    mkdir="mkdir -p"

# Pacman / yay
alias \
    p="sudo pacman" \
    pyu="sudo pacman -Syu" \
    y="yay --removemake --provides=false --answerdiff None --answerclean None --mflags '--noconfirm'" \
    rmpkg="sudo pacman -Rdd" \
    ph="bat /var/log/pacman.log" \
    fixpacman="sudo rm /var/lib/pacman/db.lck"

alias big='expac -H M "%m\t%n" | sort -h | nl'
alias gitpkg='pacman -Q | grep -i "\-git" | wc -l'
alias cleanup='orphans=$(pacman -Qtdq); [ -n "$orphans" ] && sudo pacman -Rns $orphans'
alias exr="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -100 | nl"

# Neovim
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Utilities
alias \
    ..="cd .." \
    ...="cd ../.." \
    ....="cd ../../.." \
    .....="cd ../../../.." \
    ......="cd ../../../../.." \
    v="$EDITOR" \
    vi="$EDITOR" \
    ls="eza" \
    eza="eza --color=always --group-directories-first" \
    l="eza" \
    ll="eza -lht modified" \
    lll="eza -alht modified" \
    lr="eza -R" \
    lt="eza -aT" \
    l.="eza -ald .*" \
    lh="eza -lhs modified | head -n 40" \
    lhr="eza -lrhs modified | head -n 40" \
    t="eza --tree" \
    g="grep -i --color=auto" \
    lg="ls | grep -i --color=auto" \
    cat="bat" \
    c="cat" \
    rmr="rm -r" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    gi="git" \
    gst="git status" \
    gcl="git clone" \
    gdi="git diff" \
    gad="git add" \
    glo="git log" \
    gre="git restore" \
    gcm="git commit -m" \
    gca="git commit -a" \
    gpu="git push" \
    ytdl="yt-dlp" \
    ncdu="ncdu --color off" \
    rs="rsync -rvP" \
    fd="fd --unrestricted" \
    wi="vim -c VimwikiIndex" \
    sca="scrcpy" \
    pgr="nvimpager" \
    fatsort="sudo fatsort -L en_US.UTF-8" \
    tarnow="tar -acf" \
    untar="tar -xvf" \
    wget="wget -c" \
    hw="hwinfo --short"

# Power management
alias \
    sus="systemctl suspend" \
    rbt="systemctl reboot" \
    pwr="systemctl poweroff"

# Radio
alias \
    wup="nmcli radio wifi on" \
    wdown="nmcli radio wifi off" \
    bup="rfkill unblock bluetooth" \
    bdown="rfkill block bluetooth"

# SSHFS
alias \
    pcm="sshfs mrcl@192.168.15.7:/ /media/pc" \
    pc="cd /media/pc && ls"

# Media player
alias \
    mm="mpv --profile=music"
