#!/bin/sh

# open files with fzf
o() {
	open "$(find -type f | fzf)"
}

# cd with fzf
fcd() {
	cd "$(find -type d | fzf)"
}

# Autogenerate .m3u playlist files
play() {
	for f in *.mp3; do echo "$f" >> play.m3u; done
}

# Convert magnet links into .torrent files
mag2torrent() {
	aria2c --bt-metadata-only=true --bt-save-metadata=true --listen-port=6881 "$1"
}

# Open another terminal on the current working directory
smdir() {
	setsid -f "$TERMINAL"
}

# Play a random internet radio station
radio() {
	pkill mpv; cat ~/.local/share/internetradio | shuf | sed -n 1p | xargs bgmus
}
