#!/bin/bash
# Install yay, xorg server, fonts, theme, zsh shell, and other software
# sudo needs to be set up for this to work
git clone https://aur.archlinux.org/yay-bin.git

cd yay-bin
makepkg -si

yay -Y --devel --combinedupgrade --batchinstall --save

yay -S --removemake --provides=false --answerdiff None --answerclean None --mflags "--noconfirm" aria2 bat beets bc docx2txt exiv2 fd fzf highlight htop-vim imagemagick keepassxc lf mediainfo moreutils mpc mpd mpv ncdu ncmpcpp nicotine+ noto-fonts noto-fonts-emoji nsxiv odt2txt pamixer pass pmount poppler qbittorrent qbittorrent-nox qutebrowser-git ripgrep rsm rsync simple-scan subdl surfraw syncthing task-spooler ttf-baekmuk ttf-hanazono unzip urlscan w3m wget yt-dlp zathura zathura-pdf-mupdf zip zsh zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting mullvad-vpn-bin sshfs ntfs-3g firefox opendoas eza python-adblock
