#!/bin/sh
# Install yay, xorg server, fonts, theme, zsh shell, and other software
# sudo needs to be set up for this to work
git clone https://aur.archlinux.org/yay-bin.git

cd yay-bin
makepkg -si

yay -Y --devel --combinedupgrade --batchinstall --save

yay --removemake --noprovides --answerdiff None --answerclean None --mflags "--noconfirm" abook arandr aria2 bat beets bc clipnotify docx2txt dunst exiv2 fd ffmpeg fzf gtk-theme-arc-gruvbox-git highlight htop-vim imagemagick keepassxc libnotify lf-bin maim man-db mediainfo moreutils mpc mpd mpv ncdu ncmpcpp nicotine+ noto-fonts noto-fonts-emoji nsxiv odt2txt opendoas otf-hermit pamixer pass pinentry-dmenu pmount poppler pulseaudio pulseaudio-alsa pulsemixer python-adblock python-pip qbittorrent qbittorrent-nox qt5-webengine-widevine qutebrowser ripgrep rsm rsync simple-scan socat soundconverter subdl surfraw sxhkd syncthing task-spooler ttf-baekmuk ttf-hanazono ttf-linux-libertine ttf-symbola-free unclutter unzip urlscan w3m wget xcape xclip xdotool xorg-xbacklight xorg-server xorg-xinit xorg-xsetroot xsel yt-dlp zathura zathura-pdf-mupdf zip zsh zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting

# Clone x session software repositories
# and move them to the src folder
git clone https://github.com/graupe/brownout
git clone https://github.com/cdown/clipmenu
git clone https://github.com/mars31heaven/dmenu
git clone https://github.com/mars31heaven/dwm
git clone https://github.com/mars31heaven/st

mkdir -p ~/.local/src
mv brownout clipmenu dmenu dwm st ~/.local/src/
