#!/bin/bash
# Install yay, xorg server, fonts, theme, zsh shell, and other software
# Clone repositories and move them to the src folder

git clone https://aur.archlinux.org/yay-bin.git

cd yay-bin
makepkg -si

yay -Y --devel --combinedupgrade --batchinstall --save
yay -Syu abook arandr aria2 arkenfox-user.js bat beets bc clipnotify docx2txt dunst exiv2 fd ffmpeg fzf gtk-theme-arc-gruvbox-git highlight htop-vim imagemagick keepassxc libnotify librewolf-bin lf-bin lfs maim man-db mediainfo moreutils mpc mpd mpv ncdu ncmpcpp nicotine+ noto-fonts noto-fonts-emoji nsxiv odt2txt opendoas openssh otf-hermit pamixer pass pinentry-dmenu pmount poppler pulseaudio pulseaudio-alsa pulsemixer python-adblock python-pip qbittorrent qbittorrent-nox qt5-webengine-widevine qutebrowser reaper ripgrep rsm rsync simple-scan socat soundconverter subdl surfraw sxhkd syncthing task-spooler thunderbird ttf-baekmuk ttf-hanazono ttf-linux-libertine ttf-symbola-free unclutter unzip urlscan w3m wget xcape xclip xdotool xorg-xbacklight xorg-server xorg-xinit xorg-xsetroot xsel yt-dlp zathura zathura-pdf-mupdf zip zsh zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting

cd ..
rm -rf yay-bin

git clone https://github.com/graupe/brownout \
	https://github.com/cdown/clipmenu \
	https://github.com/mars31heaven/dmenu \
	https://github.com/mars31heaven/dotfiles \
	https://github.com/mars31heaven/dwm \
	git clone https://github.com/mars31heaven/st

mkdir -p ~/.local/src
mv brownout clipmenu dmenu dotfiles dwm st ~/.local/src/
