#!/bin/bash

mv $HOME/dotfiles $HOME/.dotfiles

mkdir -p $HOME/.config/git \
    	$HOME/.config/htop \
	$HOME/.config/lf \
	$HOME/.config/mpv \
	$HOME/.config/nvim/autoload \
	$HOME/.config/shell \
	$HOME/.config/yt-dlp \
	$HOME/.config/zathura \
	$HOME/.config/zsh

ln -s $HOME/.dotfiles/zshenv $HOME/.zshenv

ln -s $HOME/.dotfiles/config/git/config $HOME/.config/git/config
ln -s $HOME/.dotfiles/config/gtk-2.0 $HOME/.config/gtk-2.0
ln -s $HOME/.dotfiles/config/gtk-3.0 $HOME/.config/gtk-3.0
ln -s $HOME/.dotfiles/config/htop/htoprc $HOME/.config/htop/htoprc
ln -s $HOME/.dotfiles/config/lf/lfrc $HOME/.config/lf/lfrc
ln -s $HOME/.dotfiles/config/lf/preview $HOME/.config/lf/preview
ln -s $HOME/.dotfiles/config/lf/shortcutrc $HOME/.config/lf/shortcutrc
ln -s $HOME/.dotfiles/config/mpv/input.conf $HOME/.config/mpv/input.conf
ln -s $HOME/.dotfiles/config/mpv/mpv.conf $HOME/.config/mpv/mpv.conf
ln -s $HOME/.dotfiles/config/nvim/autoload/plug.vim $HOME/.config/nvim/autoload/plug.vim
ln -s $HOME/.dotfiles/config/nvim/init.vim $HOME/.config/nvim/init.vim
ln -s $HOME/.dotfiles/config/shell/aliasrc $HOME/.config/shell/aliasrc
ln -s $HOME/.dotfiles/config/shell/functionrc $HOME/.config/shell/functionrc
ln -s $HOME/.dotfiles/config/shell/inputrc $HOME/.config/shell/inputrc
ln -s $HOME/.dotfiles/config/shell/shortcutrc $HOME/.config/shell/shortcutrc
ln -s $HOME/.dotfiles/config/yt-dlp/config $HOME/.config/yt-dlp/config
ln -s $HOME/.dotfiles/config/zathura/zathurarc $HOME/.config/zathura/zathurarc
ln -s $HOME/.dotfiles/config/zsh/zshrc $HOME/.config/zsh/.zshrc

mkdir -p $HOME/.cache/zsh
touch $HOME/.cache/zsh/history
