" vim-plug plugin manager
" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'vimwiki/vimwiki'
Plug 'ap/vim-css-color'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'preservim/nerdtree'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" General theme
colorscheme gruvbox

" Leader key
let mapleader =","

" Basic configuration
set nocompatible
set number relativenumber
set clipboard+=unnamedplus
set background=dark
" Turn on syntax highlighting and indentation
syntax on
filetype indent on
" This is for the vimwiki plugin
filetype plugin on
" Disable the default Vim startup message
set shortmess+=I
" Disable Ex mode
nmap Q <Nop>
" Always show the status line at the bottom
set laststatus=2
" Backspace over anything
set backspace=indent,eol,start
" Enable hidden buffers
set hidden
" Case-insensitive search when all characters in the string being search are
" lowercase. Case-sensitive if it contains any capital letters.
set ignorecase
set smartcase
" Enable searching while typing
set incsearch
" Enable autocompletion:
set wildmode=longest,list,full
" Group all swp files and backups into a dir
set backupdir=~/.vim/backups
set directory=~/.vim/backups
" Disables automatic commenting on newline:
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" Perform dot commands over visual blocks:
vnoremap . :normal .<CR>

" Replace all alias
nnoremap <leader>S :%s//g<Left><Left>
" Open files with fzf
nnoremap <leader>o :F ~<CR>
" Open ~/.dotfiles with fzf
nnoremap <leader>df :F ~/.dotfiles<CR>
" Open vimwiki index
map <leader>w :VimwikiIndex<CR>
" Open vimwiki diary index
map <leader>D :VimwikiDiaryIndex<CR>
" English spell-check set to <leader>en:
map <leader>en :setlocal spell! spelllang=en_us<CR>
" Portuguese spell-check set to <leader>pt:
map <leader>pt :setlocal spell! spelllang=pt_br<CR>
" Shortcuts for split navigation:
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" New tab shortcut
map <leader>t :tabnew<CR>

" Vimwiki and Calcurse configuration
let g:vimwiki_ext2syntax = {'.Rmd': 'markdown', '.rmd': 'markdown','.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
let g:vimwiki_list = [{'path': '~/docs/vimwiki', 'syntax': 'markdown', 'ext': '.md'}]
autocmd BufRead,BufNewFile /tmp/calcurse*,~/.calcurse/notes/* set filetype=markdown

" Automatically deletes all trailing whitespace and newlines at end of file on save.
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre * %s/\n\+\%$//e
autocmd BufWritePre *.[ch] %s/\%$/\r/e

" Run xrdb whenever Xdefaults or Xresources are updated.
autocmd BufRead,BufNewFile Xresources,Xdefaults,xresources,xdefaults set filetype=xdefaults
autocmd BufWritePost Xresources,Xdefaults,xresources,xdefaults !xrdb %

" NERDTree configuration and shortcuts
let NERDTreeShowHidden=1
nnoremap <leader>N :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>

" limelight configuration
let g:limelight_conceal_ctermfg = 'gray'
let g:limelight_conceal_ctermfg = 240

" Toggle limelight plugin
nnoremap <leader>l :Limelight!!<CR>

" Toggle Goyo plugin
nnoremap <leader>g :Goyo<CR>
