#!/bin/sh
while read file
do
        case "$1" in
		"c")
			cp "$file" ~ ;;
		"d")
			rm "$file" ;;
		"e")
			display "$file" ;;
		"m")
	      		mv "$file" ~ ;;
		"r")
			convert -rotate 90 "$file" "$file" ;;
        	"R")
	      		convert -rotate -90 "$file" "$file" ;;
        	"w")
              		xwallpaper --zoom "$file" ;;
        	"y")
              		echo -n "$file" | xclip -selection clipboard ;;
	esac
done
