position = "top"
anchor_to_edges = true
height = 28

[[start]]
type = "workspaces"
all_monitors = false

[[center]]
type = "focused"
show_icon = true
show_title = true
icon_size = 22
truncate = "end"

[[end]]
type = "music"
player_type = "mpd"
format = "{artist} - {title}"
music_dir = "/home/mrcl/05_music"
show_status_icon = true

[[start.icons]]
play = ""
pause = ""

[[end]]
type = "clock"
format = "%d/%m/%Y %H:%M"
