# ── External configuration ───────────────────────────────────

for file in \
    "$HOME/.config/shell/aliasrc" \
    "$HOME/.config/shell/shortcutrc" \
    "$HOME/.config/shell/functionrc" \
    "$HOME/.config/shell/private"
do
    [ -f "$file" ] && source "$file"
done


# ── Prompt ────────────────────────────────────────────────────

autoload -U colors && colors
PS1=' %F{red}%~%f $ '


# ── History ───────────────────────────────────────────────────

HISTSIZE=100000
SAVEHIST=100000

setopt append_history
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_expire_dups_first

# Don't pollute history with routine navigation/helpers.
zshaddhistory() {
    local command=${1%%$'\n'*}
    local first_word=${command%%[[:space:]]*}

    case "$first_word" in
        ls|l|ll|lll|lr|lt|l.|lh|lhr|t|o|fcd|lfcd|ipa)
            return 1
            ;;
    esac

    return 0
}


# ── Shell behavior ────────────────────────────────────────────

setopt autocd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus
setopt globdots
setopt extendedglob
setopt nocaseglob
setopt interactive_comments
setopt nocheckjobs
setopt numericglobsort
setopt nobeep
setopt correct


# ── Completion ────────────────────────────────────────────────

autoload -Uz compinit
compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true


# ── Vi mode ───────────────────────────────────────────────────

bindkey -v
KEYTIMEOUT=1

bindkey '^?' backward-delete-char
bindkey '^[[3~' delete-char


# ── History search ────────────────────────────────────────────

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down


# ── FZF ───────────────────────────────────────────────────────

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh


# ── Plugins ───────────────────────────────────────────────────

source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

typeset -g HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=default,fg=magenta,underline'
typeset -g HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=default,fg=yellow,underline'

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
