#!/bin/sh

remaps &
xbacklight -set 10%
unclutter -noevents -root &
clipmenud &
sxhkd &
batsignal -c 10 -d 8 -f 100 -D "doas zzz" -e &
sbar &
xrdb .config/x11/xresources
xset s 480
xsetroot -solid "#282828"
brownout 600
exec dwm

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
